"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

DATA_FILES = ['data']
OPTIONS = {'argv_emulation': True, 'compressed': True, 'iconfile': '1337ris.icns'}
NAME = '1337ris'

plist = dict(
    CFBundleName=NAME,
    CFBundleShortVersionString='v2.0',
    CFBundleExecutable=NAME,
    CFBundleIdentifier='htwcoder.1337ris',
    CFBundleSignature='l337',
    NSHumanReadableCopyright='Written by Henry Weiss'
)

setup(
    app=[dict(script="1337ris.py", plist=plist)],
    data_files=DATA_FILES,
    extra_modules=['pygame.locals'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'pygame']
)
